### ISSUE TITLE
显示没有标题

### ISSUE THREAD

**Issue by 70loKirin** [Dreamer-Paul/Hingle#6]
非常感谢你的主题，很喜欢！简约而不简单

我使用的时候遇到一个问题不知道该怎么做
![image](https://user-images.githubusercontent.com/91271243/207515438-90e58dea-562c-4b76-abfb-450e0d5d55ae.png)
在点击`关于我`和`朋友们`时会显示没有标题，如上图
我尝试使用
```
---
title: About Me
---

# About Me
```
但是还是显示没有标题

**Comment by Dreamer-Paul** [comment]
复现成功了，这个问题后续跟进

**Comment by Dreamer-Paul** [comment]
试试看有没有问题？

**Comment by 70loKirin** [comment]
okok 已经好了，谢谢
